# PostgreSQL Configuration
postgresql:
  enabled: true 
  postgresService: postgres
  postgresUser: postgres
  postgresPassword: postgres
  postgresDatabase: app
  postgresPort: 5432
  postgresStorageSize: 10Gi
  image:
    repository: postgres  
    tag: 13  

# Application Configuration
webapp:
  replicaCount: 1 
  containerPort: 8082
  image:
    repository: quay.io/csye7125group3/webapp-images  # Your application image repository
    tag: latest  # Your application image tag
  imagePullPolicy: IfNotPresent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  minReadySeconds: 45
  progressDeadlineSeconds: 90
  readinessProbePath: v1/actuator/health/readiness 
  livenessProbePath: v1/actuator/health/liveness



configMap:
  enabled: true
  name: webapp-config

secrets:
  imagePullSecrets: {{ .Release.Name | quote }}-pull-secret
  postgresPassword: postgres-secrets
  name: postgres-secrets
  data:
    postgresPassword: DB_PASSWORD
