apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pull-secret-oper
  namespace: webapp
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjR0YyWVc1bllXNWxjMmgyWVhOaE9teFZVMjQ1VkU1dmVsaExZMmRPUldWNFRsa3JXbU5EVTJaeGFYRjBVMmc0ZVVsUlNrcHlWbEJaUmxaSWRraGpkVVkxV1UxTk9USjJTME5OTmxWb2JFcz0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
