apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  DB_HOST: {{ .Values.postgresql.postgresService }}.{{ .Release.Namespace }}.svc.cluster.local
  DB_PORT: {{ .Values.postgresql.postgresPort | quote }}  # Port as a string
  DB_NAME: {{ .Values.postgresql.postgresDatabase }}
  DB_USERNAME: {{ .Values.postgresql.postgresUser }}
  DB_PASSWORD: {{ .Values.postgresql.postgresPassword }}

