apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-listing-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-listing-rolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: webapp
roleRef:
  kind: ClusterRole
  name: crd-listing-role
  apiGroup: rbac.authorization.k8s.io
