apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: healthcheck-custom-resource-role
rules:
- apiGroups: ["webapp.udaykk.me"]  # CRD's API group
  resources: ["healthchecks"]  # CRD resource name
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: healthcheck-custom-resource-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default  # Replace with your ServiceAccount name
  namespace: default
roleRef:
  kind: Role
  name: healthcheck-custom-resource-role
  apiGroup: rbac.authorization.k8s.io
