apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-kafka-pvc
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 3Gi 
  storageClassName: "" 
  volumeName: {{ .Release.Name }}-postgres-kafka-pv 
