apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-kafka
  labels:
    app: postgres
spec:
  ports:
    - name: postgres
      port: 5433
  clusterIP: None
  selector:
    app: postgres
  type: ClusterIP
