apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-webapp-kafka-vs
  namespace: consumer
spec:
  hosts:
  - {{ .Release.Name }}-webapp-kafka-lb-service.consumer.svc.cluster.local
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}-webapp-kafka-lb-service.consumer.svc.cluster.local
        port:
          number: 80
