apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webapp-lb-service
  namespace: webapp
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.webapp.containerPort }}  # Adjust targetPort to match your application
  selector:
    app: webapp  # Label selector to match your pods
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webapp-deployment
  namespace: webapp
  labels:
    app: webapp
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  strategy:
    type: {{ .Values.webapp.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.webapp.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.webapp.strategy.rollingUpdate.maxUnavailable }}
  minReadySeconds: {{ .Values.webapp.minReadySeconds }}
  progressDeadlineSeconds: {{ .Values.webapp.progressDeadlineSeconds }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: {{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag }}
        ports:
        - containerPort: {{ .Values.webapp.containerPort }}
        readinessProbe:
            httpGet:
              path: {{ .Values.webapp.readinessProbePath }}
              port: {{ .Values.webapp.containerPort }}
            periodSeconds: 20
            initialDelaySeconds: 300
            failureThreshold: 10
        livenessProbe:
            httpGet:
              path: {{ .Values.webapp.livenessProbePath }}  
              port: {{ .Values.webapp.containerPort }}
            periodSeconds: 15
            initialDelaySeconds: 300
        envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-webapp-config
      imagePullSecrets:
      - name: {{ .Release.Name }}-pull-secret
