apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-webapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-webapp-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 5
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Name }}-webapp-default-limits
spec:
  limits:
  - default:
      memory: "1Gi"        # Default memory limit for containers
      cpu: "1"             # Default CPU limit for containers
    defaultRequest:
      memory: "512Mi"     # Default memory request for containers
      cpu: "0.5"          # Default CPU request for containers
    type: Container