apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-webapp-vs
  namespace: webapp
spec:
  hosts:
  - {{ .Release.Name }}-webapp-lb-service.webapp.svc.cluster.local
  gateways:
  - {{ .Release.Name }}-webapp-gateway
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}-webapp-lb-service.webapp.svc.cluster.local
        port:
          number: 80
