kind: VirtualService
apiVersion: networking.istio.io/v1alpha3 
metadata:
  name: {{ .Values.vs.name }} 
spec:
  hosts:
    - {{ .Values.ingress.host | quote }}
  gateways:
    - {{ .Values.ingress.name }}
  http:
  - route:
    - destination:
        port: 
          number: {{ .Values.webapp.servicePort }}
        host: {{ .Release.Name }}-webapp.webapp.svc.cluster.local
        subset: {{ .Values.webapp.subset }}
      weight: {{ .Values.vs.destinationWeight }}
